### ISSUE TITLE
[초급반 1회차] dp 점화식에서 i번째 원소를 무조건 포함하는지를 어떻게 구별하나요? (gracelee)

### ISSUE THREAD

**Issue by mok0102** [UNIST-Almight/PSStudy_21Fall#10]
[A번 문제](http://boj.kr/94f92423248f4cd58dc6403f86408926)
[D번 문제](http://boj.kr/170f0d9f645b42eaa6a4ffe5757f2892)

dp 문제들을 풀어보면 A번 문제처럼 dp[i]가 i번째 원소를 무조건 포함하는 경우가 있고, D번 문제처럼 포함하지 않는 경우가 있는 것 같은데 혼자 힘으로는 이 두 경우를 구별하기가 조금 힘든 것 같습니다. 혹시 이 두 가지 경우를 잘 구별할 수 있는 나름의 팁이 있다면 알려주시면 감사하겠습니다 ! 구분을 못해서 점화식을 잘못 세웠던 적이 꽤 있었습니다 ㅠㅠ

**Comment by mok0102** [comment]
레이블이 표시가 안 됩니다 ㅠㅠ!

**Comment by gdpark14** [comment]
음 테이블을 어떻게 정의 하기 나름이지 않을까요? 제 생각에는 A번 문제의 경우는 dp[i]가 i번째 원소를 무조건 포함하는 방식으로 테이블이 설계 되었다면 D번 문제의 경우에는 배낭의 무게가 i로 설정 되니까 테이블의 설계 방식에 따라 다른 것 같아요. 개인적으로 D번 문제의 테이블 설계 방식은 혼자 생각해내기가 어려웠습니다..

**Comment by JinLover** [comment]
제 개인적인 생각으로는 A번의 경우에는 **연속된** 수열이라는 조건이 있었기에 DP식을 짜려면 반드시 i번째 원소가 포함되어야 하는 것 같습니다. 하지만 D번 문제에는 그러한 조건이 없기에 i번째 원소가 포함되지 않는 것이 아닐까 생각해 봅니다.

**Comment by docsom** [comment]
D번 문제 간결하게 잘 푸신 것 같아요
저도 dp는 아직 많이 어렵네요.. 느낌이 문제를 많이 풀어봐야 할 것 같아요
