### ISSUE TITLE
[초급반 1회차] B번 문제 코드 리뷰 요청 (ajm6962)

### ISSUE THREAD

**Issue by ahnjongmin** [UNIST-Almight/PSStudy_21Fall#11]
http://boj.kr/88feac21fc804d2991293c860bff0e93

궁금한 점이 한 가지 있어요.
이 문제의 경우에는 DP가 해결방법이라는 걸 아는 채로 풀었기 때문에 비교적 무난하게 해결할 수 있었는데,
이 사실을 모른다면, 과연 이 풀이를 생각해낼 수 있을지 잘 모르겠네요.
혹시 다른 분들은 문제만 봐도 패턴이 보이시는 지가 궁금해요.
이건 그냥 많이 풀어봐야 해결되는 문제일까요?

**Comment by gdpark14** [comment]
i번째 숫자 까지의 답을 구할 때 i-1 번째 까지의 답을 활용 한다면 DP를 의심해 볼 수 있지 않을까요?

------
그럼 혹시 DP와 Greedy의 차이점은 매 step 마다 여러 case들을 고려한 뒤에 값을 저장하는 것이 DP이고 여러 case가 아닌 하나의 특정한 solution이 존재하는게 greedy algorithm이라고 볼 수 있을까요?

**Comment by gwannuu** [comment]
위의 분의 답변에 대댓글을 달자면 제 생각에는 DP와 greedy의 차이는 memorization의 유뮤인 것 같습니다. DP의 경우에는 memorization이 필수로 요구되는 반면 greedy는 memorization 없이도 알고리즘 만으로 문제 해결이 되는 것 같습니다.

**Comment by JinLover** [comment]
저같은 경우는 그리디와 DP간의 구별은 어떤 순간의 최적해가 전체 문제의 최적해가 되는가를 생각을 해 봅니다. 이 문제같은 경우 i번째 숫자중에서 최적해를 구한다고 해서, 그것이 i+1번째에서도 최적해가 되지는 않기 때문에 그리디로는 풀 수 없습니다.
ex) ```1 0 -5``` 중 최적해는 (1, 0) = 1이지만
     ```1 0 -5 10``` 이 된다면 최적해가 (10) = 10이 되버리면서 이전까지의 최적해와는 아무 관련이 없게 됩니다.

**Comment by nngm** [comment]
저는 문제를 먼저 보고 첫째로 '이걸 그리디로 풀 수 있을까?' 하고 고민해보고 안 되면 그 다음으로 '그럼 이건 DP 문제일까?' 하고 생각해 봅니다. 이렇게 하면 바로 풀이를 떠올릴 수 있지 않을까요?
@gwannuu 그리고 memorization이 아니라 memoization입니다! 메모를 한다는 뜻이죠
