### ISSUE TITLE
[초급반 1회차] A번 문제 코드 리뷰 요청 (cgw1999)

### ISSUE THREAD

**Issue by gwannuu** [UNIST-Almight/PSStudy_21Fall#12]
![2](https://user-images.githubusercontent.com/83270461/132238336-c4826638-1724-4d95-994b-713e05c6f498.png)
![1](https://user-images.githubusercontent.com/83270461/132238339-c04f7eda-de5c-4f13-a5ca-a0e804308085.png)

첫번째 사진처럼  풀이를 작성할경우 오답처리되는데
두번째 사진처럼 풀이를 작성할 경우 정답처리 됩니다

그 이유를 잘 모르겠어서 질문드립니다

**Comment by nukeC919** [comment]
N = 1 일 때를 생각해봅시다.

먼저 첫번째 코드부터,
제가 C언어를 안해서 잘 모르는데, 전역 변수는 0으로 초기화 된다고 들었습니다.
그리고 입력을
```
1
10
```
이렇게 받았다고 해봅시다.
```c
for( int i=1 ; i<=n ; ++i ) { cin >> arr[i] ; } // arr = { 0 , 10 }
for( int i=1 ; i<=n ; ++i ) { DP[i] = 1 ; } // DP = { 0 , 1 }
for( int i=1 ; i<=n ; ++i ) {
    for( int j=1 ; j<i ; ++j ) { 
        ...
    }
}
```
3번째 for 문부터 문제가 발생합니다.
n = 1 이므로 3번째 for문은 i = 1 단 하나만 작동합니다.
4번째 for문에서 `j = 1 < 1` 이 성립하지 않으므로 아예 작동을 하지 않습니다.
즉, 4번째 for문 안에 있는 `ans = ...` 코드가 작동하지 않아서
답은 1을 출력해야 하는데 초기값인 0을 출력해버립니다.

하지만 2번째 코드는 `ans = ...` 코드가 4번째 for문 밖에 있기에 작동할 수 있습니다.
