### ISSUE TITLE
[초급반 2회차] D번 코드리뷰 요청

### ISSUE THREAD

**Issue by gdpark14** [UNIST-Almight/PSStudy_21Fall#13]
글 작성시 Label을 첨부하는 톱니바퀴 모양이 뜨지 않는데 혹시 해결방법 아시나요?

```
import sys
import collections

n,l,i=map(int,sys.stdin.readline().split())

def check(num,comp):
    temp=num
    count=0
    while temp>1:
        if temp%2==1:
            count+=1
        temp=temp//2
    if temp==1:
        count+=1
    if count>comp:
        return 1
    else:
        return 0

dp=[0]*(i+1)
dp[1]=0
for k in range(2,i+1):
    temp=dp[k-1]+1
    if check(temp,l)==1:
        num=temp
        while check(num,l)==1:
            num+=1
        dp[k]=num
    else:
        dp[k]=dp[k-1]+1
```

우선 위와 같이 코드를 짰었습니다.
dp[k]는 비트 1의 갯수가 l 이하인 k번째 숫자로 정의 했습니다.
check(num,comp)함수는 num을 이진수로 바꿨을 때 1의 갯수가 comp이하인지를 체크하는 함수로 정의했습니다.
그래서 dp[k]는 dp[k-1]+1이거나 dp[k-1]+1이 check를 만족하지 못하면 while을 통해 만족하는 num까지 찾은뒤 dp[k]=num
이런식으로 코드를 짰습니다.
dp[-1]이 그럼 해당 조건을 만족하는 i번째 숫자가 되겠고 이를 이진수로 바꾸면 된다고 생각했습니다.(위의 코드에는 없음)

그런데 이렇게 풀다보니 메모리초과가 나왔습니다.  메모리초과가 어디서 발생하는지와 메모리초과 이슈가 발생하지 않더라도 위의 코드는 틀린 것인지 여부가 궁금합니다.

**Comment by mskim-17** [comment]
N과 L이 각각 31로 주어졌을 경우 I의 값은 최대 2<sup>31</sup> (약 21억) 까지 나올 수 있기 때문에 dp 배열의 크기를 I+1로 잡으면 메모리 초과가 나며, 충분한 메모리가 주어지더라도 마지막 for문에서 시간 초과가 나게 됩니다. 가능한 모든 이진수를 확인하는 방법이 아닌 다른 방법으로 접근해야 주어진 시간과 메모리 내로 문제를 해결할 수 있습니다.

**Comment by Raon1123** [comment]
김민서님이 지적하신대로 I의 최대값에서 문제가 발생합니다. 2의 31승이여서 매우 큽니다.
파이썬의 경우 정수 자료형 표현에 대해서 정확하게 구하기는 어렵지만, 32bit보다는 보통 많이 할당하여 쉽게 메모리 초과가 뜨게 됩니다.
