### ISSUE TITLE
[중급반 2회차] E번 문제 코드 리뷰 (ace9804)

### ISSUE THREAD

**Issue by DDoubleA** [UNIST-Almight/PSStudy_21Fall#14]
[18513번 샘터] http://boj.kr/a3a5b53b718d4b99811881b7ffb60825

샘터의 위치의 범위가 (-100,000,000 ≤ 샘터의 위치 ≤ 100,000,000)이고 K의 범위가 100,000 입니다.
그래서 집의 범위는 (-100,050,000 ≤ 집의 위치 ≤ 100,050,000)라고 생각했고 -index를 갖는 배열을 만들 수 없어 100,050,000을 더해 (0 ≤ 집의 위치 ≤ 200,100,000)의 배열을 만들어 방문한 지점을 체크하며 탐색을 하여 답을 구했습니다. 
위와 같은 방법으로 해서 통과는 했으나 큰 배열을 만들어 메모리를 많이 사용한 것 같습니다. 메모리를 적게 쓰며 문제를 풀 수 있는 방법을 알고 싶습니다.

**Comment by mskim-17** [comment]
방문 여부를 배열이 아닌 set으로 판단하면 메모리를 크게 줄일 수 있습니다. 다만 크기가 N인 set에서 탐색을 하는 과정은 O(log N)이기 때문에 수행 시간은 더 늘어나게 됩니다. 
https://www.cplusplus.com/reference/set/set/

**Comment by queuedq** [comment]
> 다만 크기가 N인 set에서 탐색을 하는 과정은 O(log N)이기 때문에 수행 시간은 더 늘어나게 됩니다.

Hash table을 쓰면 탐색을 O(1)에 할 수 있습니다! 파이썬에서는 dict, C++에서는 unordered_set에 해당되는 개념입니다.
