### ISSUE TITLE
[초급반 2회차] A, C번 문제 코드 리뷰 (kts0921)

### ISSUE THREAD

**Issue by docsom** [UNIST-Almight/PSStudy_21Fall#16]
[A번 문제](http://boj.kr/722e46760f644487933a243f15ea5cca)
```
int* d = new int[1000005];
int* pre = new int[1000005];
```
예전에 풀었던 '1로 만들기' 코드에 테이블을 하나 더 추가해서 경로 추적을 했습니다.
테이블 하나 더 안 만들고 경로추적 하시기도 하던데 어떤게 나은지 궁금합니다. 문제마다 다른가요?

---

[C번 문제](http://boj.kr/d01cc912e59e4a1f903153b55b5ba985)
```
string result = "";
int i = A.length(), j = B.length();
while (LCS[i][j] != 0) {
	if (LCS[i][j] == LCS[i - 1][j]) {
		i--;
		continue;
	}
	if(LCS[i][j] == LCS[i][j - 1]) {
		j--;
	}
	else {
		result = A[i - 1] + result;
		i--;
		j--;
	}
}
cout << result;
```
저번주 LCS 문제 코드에 2차 배열 맨 오른쪽 아래에서 숫자 0을 만날때까지의 경로를 따라 스트링을 만들어서 출력했습니다.
보시고 자유롭게 피드백 주세요.

**Comment by wbjeon2k** [comment]
dp traceback 에 대한 일반적인 방법론 입니다. 제가 예전에 공부하다가 본 다른 분의 말씀입니다.
> 저는 updateDP(index, from, val) 함수를 애용합니다. DP[index]의 값이 val로 새로 update 되야 하는 상황이라면 RDP[index]에 from index를 저장해요 그러면, RDP만을 이용해서, 역추적이 가능하죠

일반적으로는 위 방법같이, traceback 을 위한 정보를 따로 저장 해야합니다.
dp table 만을 보고도 traceback 이 가능한 상황에는 따로 pre 등을 사용할 필요는 없지만,
제 기억에 매우 단순하거나 아주 특이한 경우가 아니라면, traceback table 을 따로 사용하시는게 더 좋다고 생각합니다.

ps. 동적 할당은 안쓰셔도 될 것 같습니다. 굉장히 불편해 보입니다...

**Comment by queuedq** [comment]
@wbjeon2k backtrack이 아니라 traceback입니다! Backtracking은 중급반 1회차/초급반 3회차에서 배우는 개념으로, 재귀적으로 조건을 만족하는 답의 후보인지 체크하며 모든 답을 방문하는 과정이고, DP 역추적은 백트래킹과는 다른 개념으로 traceback이라고 부릅니다. 비슷한 이름이라 잘못 설명된 자료가 종종 있어서 헷갈리시는 분들이 많더라고요.

그리고 wbjeon2k님 말씀대로 C++에서는 동적 할당은 비추천드립니다. 고정된 크기의 전역 배열을 선언하거나, 전역 스코프를 더럽히기 싫다면 vector를 사용해 주세요. 직접 메모리를 관리하지 않아도 돼서 편리합니다.

**Comment by mok0102** [comment]
@wbjeon2k 님이 여기로 태그해 주셔서 읽으러 왔습니다 ㅎㅎ 막상 생각나는 방법이 pair를 써서 역추적 하는 방법밖에 없어서 그렇게 풀었었는데, 보통은 array를 하나 더 선언하신다고 알려주셔서 코드 보고 어떻게 하는지 열심히 배웠습니다 ! 한 문제에 대해서도 여러 방법이 나오고 서로 공유할 수 있으니까 굉장히 좋은 것 같습니다 😊 많이 배워갑니다 !!
