### ISSUE TITLE
[초급반 2회차] A번 문제 코드 리뷰 (gracelee)

### ISSUE THREAD

**Issue by mok0102** [UNIST-Almight/PSStudy_21Fall#17]
[A번](http://boj.kr/d39fe01257e84be6b29b259371e3809a)

이 문제에서 저는 dp를 pair로 선언해서 dp[i]가 바로 전에 쓰였던 i를 저장하도록 해서 풀었습니다. 그래서 1로 만드는 방법에 포함되어 있는 수를 출력할 때 n을 나눠 가면서 하나씩 출력하도록 해서 문제를 풀었었습니다.
그런데 이 방법 말고 아예 array를 하나 선언해서 그 array에 바로 1로 만드는 방법에 포함되어 있는 수를 저장할 수 있는 코드가 있을까요? 그리고 또  보통 이런 문제를 풀때 pair를 쓰는지, 아니면 2차원 배열을 선언하는지, 아니면 아예 벡터를 사용하는지도 궁금합니다.

**Comment by wbjeon2k** [comment]
일반적으로는 backtrack 용 table을 따로 만듭니다.
https://github.com/UNIST-Almight/ps-study-2021-fall/issues/16#issuecomment-918152019
링크 참고 해주세요!

**Comment by docsom** [comment]
저는 array를 하나 더 선언했는데 pair를 쓰는 방법도 있었네요 👍

**Comment by gdpark14** [comment]
일반적으로 backtrak을 위해서 table을 하나 새로 만든다고 알고 있습니다. 혹시 array를 따로 만들지 않고 pair를 쓰면 더 좋은 점이 있을까요?

**Comment by jjh94210** [comment]
Pair로 짜여진 코드가 신기하네요 👍 Table에 비해 메모리를 과다하게 많이 먹지는 않나요? 🔢
