### ISSUE TITLE
[초급반 2회차] A번 코드 리뷰 (raonmire)

### ISSUE THREAD

**Issue by Raon1123** [UNIST-Almight/PSStudy_21Fall#18]
[코드 전문](http://boj.kr/f5dbb3fdd91b4838b5ba53921d5b9789)

이번 문제 집합의 테마가 DP테이블을 완성하고 DP테이블을 추가적으로 활용하여야 하는 문제였습니다.
1로 만들기 문제도, 횟수를 찾는 것을 넘어서서 횟수를 만드는 과정을 찾아야 합니다.

DP테이블을 활용하여, 각 index 별로 1로 만드는 횟수를 저장하였습니다.
그렇다면, 이를 N부터 거꾸로 찾아가는 과정을 어떻게 구할 수 있을까요?
다음 과정의 경우 1로 만드는 횟수가 이전의 횟수보다 하나 작을 것입니다.
그렇게 DP테이블이 완성되었다면, 이를 역으로 활용하여서 찾았습니다.

이를 더 개선시킬 방법이 있을까요?

**Comment by DDoubleA** [comment]
dp테이블을 채우는 과정에서 다른 코드들과 다르게 i 번째 칸에서 i-1. i/2, i/3 값을 참고해 i번째 칸을 채우는 것이 아니라 bfs처럼 i번째 칸에서 i+1, ix2, ix3을 채우는 것도 신기했고 traceback을 위한 테이블을 따로 만들지 않고  i-1. i/2, i/3의 cnt를 비교해 가며 역추적하는 것도 신기했습니다.

**Comment by JinLover** [comment]
`다음 과정의 경우 1로 만드는 횟수가 이전의 횟수보다 하나 작을 것입니다.` 이 아이디어가 신기하네요! 저는 하나의 DP에 이전까지 쓰인 값들을 모두 저장하는 방식을 생각했는데, 아직은 성공하지 못했습니다 😂

**Comment by jjh94210** [comment]
혹시 INIT이 987654321인 특별한 이유가 있나요? 👍

**Comment by Raon1123** [comment]
@jjh94210 
아마도 이 방법이 구종만책 "알고리즘 문제 해결 전략"에 소개되었을텐데요.
그냥 큰 숫자인데 0을 세기에는 까다로우니 저렇게 적는것으로 압니다.
또한 제일 큰 숫자가 저것보다는 작아서 MAX를 그렇게 해도 되고요.
