### ISSUE TITLE
[중급반 2회차] A번 문제 코드 리뷰 (flame623) 

### ISSUE THREAD

**Issue by JinLover** [UNIST-Almight/PSStudy_21Fall#19]
http://boj.kr/63364a8cc9d74ef5a2d56d423b867d26
물도 마치 고슴도치처럼 움직인다고 생각해서, 고슴도치가 움직인 경로에는 움직인 숫자를 저장하고, 물은 돌과 도착지점을 제외하면 같이 퍼져나가게 구현해서 해결하였습니다.

**Comment by DDoubleA** [comment]
문제 풀이 세션 때 고슴도치 이동과 물 이동을 한 턴씩 진행한다고 하셔서 어떻게 짰는지 자세히 보고 싶었는데 깔끔하고 좋네요. 파이썬 코드가 확실히 읽기 편한 것 같습니다.

**Comment by Raon1123** [comment]
적절한 변수명을 통하여 무엇이 어떻게 해결하고자 하는지 명쾌하게 드러내는 좋은 코드네요 :)
