### ISSUE TITLE
[중급반 2회차] B번 문제 코드 리뷰 (cgw1999)

### ISSUE THREAD

**Issue by gwannuu** [UNIST-Almight/PSStudy_21Fall#20]
저는 이 문제를 풀 때

수열을 입력할 때 이전 인덱스를저장하는 priors[] 라는 배열과
stack 자료구조를 이용해서 수열을 출력하였는데

http://boj.kr/4c68c82a57074a058acd478327cd9884

다른분들은 어떻게 하셨는지 궁금합니다

**Comment by queuedq** [comment]
코드 우측 하단 공유하기 버튼을 눌러서 코드를 공유해 주세요! 현재 링크는 문제를 못 푼 사람은 확인할 수 없게 되어 있어요.

**Comment by gwannuu** [comment]
아 그렇군요, 알려주셔서 감사합니다 :)
