### ISSUE TITLE
[초급반 3회차] C번 문제 코드 리뷰

### ISSUE THREAD

**Issue by gdpark14** [UNIST-Almight/PSStudy_21Fall#21]
C번에서 해당 암호의 모음이 1개이상, 자음이 2개 이상인 조건을 아래의 함수로 체크하였습니다.
```
def check(comp):
    check_list=['a','e','i','o','u']
    count_m=0
    count_j=0
    for i in comp:
        if i in check_list:
            count_m+=1
        else:
            count_j+=1
    if count_m>=1 and count_j>=2:
        return 1
    else:
        return 0
```
코드 전문 : http://boj.kr/59b2558499104fb8861ff754d13d5365

이렇게 함수로 체크 하는 것 말고 좀 더 깔끔한 방법이 있을까요?

**Comment by nukeC919** [comment]
저 방법은 DFS 에서 가능한 모든 순열에서 걸러내는 방법입니다.
하지만 DFS 안에서 count 를 함으로써 모든 순열을 찾지 않아도 됩니다.
```py
def DFS( code , ja , mo , idx , codeLen ) :
    if codeLen == L :   # 암호 길이가 L 일때 암호를 출력
        print(code)
        return
    for i , apb in enumerate( alphabet[idx:] ) :   # enumerate() 는 idx 와 value 를 한번에 for 변수로 둘 수 있습니다.
        if apb in ['a','e','i','o','u'] :   # 모음일 때
            if L - mo <= 2 : continue   # 자음이 존재할 수 있는 자리가 2개 이하일 때 continue
            DFS( code+apb , ja , mo+1 , idx+i+1 , codeLen+1 )
        else :   # 자음일 때
            if L - ja <= 1 : continue   # 모음이 존재할 수 있는 자리가 1개 이하일 때 continue
            DFS( code+apb , ja+1 , mo , idx+i+1 , codeLen+1 )
```
코드 전문 : http://boj.kr/5357dcc6f40f4fa08b5a3b247ba91549

`L - mo <= 2` 가 무슨 뜻이나면 최종 암호 길이에서 모음 갯수를 뺀건데,
그러면 자음이 들어갈 수 있는 최대값을 뜻하겠죠?
그런데 이 최대값이 2개 이하라면, 이번에 모음 넣을껀데 그러면 자음은 2개 이상이 될 수 없겠죠?
그래서 저 상황에 `continue` 하는겁니다.
`L - ja <= 1` 도 마찬가지 이고요.

이렇게 하면 어떤게 빨라지느냐,
L = 4 일 때, code 가 `ae` 이고 apb 가 `i` 라고 해봅시다.
저 방법에서는 `aei` 에서 `aeib` , `aeid` , ... 이렇게 계속 찾아나가겠죠.
하지만 지금 방법은 자음이 2개가 될 수 없음을 알고 `continue` 합니다.

속도가 빨라지고 코드도 좀 더 깔끔하게 됩니다.

**Comment by docsom** [comment]
저도 윗분처럼 백트래킹함수 안에서 자음 모음 개수를 처리했어요.
