### ISSUE TITLE
[중급반 3회차] G번 문제 코드 리뷰 (mskim17)

### ISSUE THREAD

**Issue by mskim-17** [UNIST-Almight/PSStudy_21Fall#22]
http://boj.kr/d337abe022664e1ea070175f1ca59102

최단 경로를 역추적하기 위해 간선이 반대 방향인 그래프를 따로 만들었고 (`graph_rev`), 최단 경로를 찾은 후에는 `shortest` 배열에 최단 경로에 포함되는 간선을 체크해 거의 최단 경로를 찾을 때 해당 간선을 무시할 수 있게 했습니다.

많은 피드백 부탁드립니다.

**Comment by Raon1123** [comment]
깔끔하게 함수별로 무슨 역할을 하고 어떠한 알고리즘을 구현했는지 표현하는 명쾌한 코드네요 :)
