### ISSUE TITLE
[초급반 3회차] B번 문제 코드 리뷰 (gracelee)

### ISSUE THREAD

**Issue by mok0102** [UNIST-Almight/PSStudy_21Fall#23]
백트랙킹이랑 재귀가 머리에 잘 들어오지 않아서 이 문제를 인터넷을 참하여 공부했는데, 이 문제를 푸는 방법이 크게 두 가지 인 것 같아서 혼자 정리해보려고 합니다! 그래서 피드백 보다는 기록에 가까운 점 양해 부탁드립니다 😊 그리고 생각보다 어려워서 잘 이해를 했는지가 확인이 힘들어서 중간중간 오류가 있다면 수정 해주시면 감사하겠습니다!

[첫 번째 방법](http://boj.kr/4e789cc86cf34c93ac885502b8b9028f)
재귀를 이용하는 방법이고, count의 sum이 목표에 도달하면 result를 하나씩 늘리는 방법입니다. sum이 목표에 도달했을 때에 바로 return을 하지 않는 이유는 이후에 또 더하고 빠지면서 목표에 도달할 수 있기 때문입니다. result로 카운팅이 끝나면 sum에 해당 i번째의 더하고 다시 count함수를 재귀로 보내는 경우와, sum에 해당 i번째를 더하지 않고 다시 count 함수를 재귀로 보내는 두 가지 경우로 나눠서 문제를 해결할 수 있습니다.

[두 번째 방법](http://boj.kr/2e87d4f91c1f418b84141d503b7b9e52)
이것 또한 재귀를 이용하는 방법인데, A, C번과 비슷한 방법인 것 같습니다. 일단 sum이 목표에 도달하면 cnt를 하나씩 늘리는 것은 동일하고, 이후에 재귀를 보내는 방법이 첫 번째 방법처럼 더한 경우와 더하지 않은 경우로 나눈 것이 아니라 idx부터 n전까지 for문을 돌면서 sum에 a[i]를 더하고, idx를 1 늘린 것을 재귀로 보냅니다. 따라서 

dfs(0+arr(0), 1) 은 dfs(arr(0)+arr(1), 2), dfs(arr(0)+arr(2), 3), dfs(arr(0)+arr(3), 4) .... 으로 경우가 쪼개지고 
dfs(0+arr(1), 2) 은 dfs(arr(1)+arr(2), 3), dfs(arr(1)+arr(3), 4), dfs(arr(1)+arr(4), 5) .... 으로 경우가 쪼개지고 
dfs(0+arr(2), 3) dfs(arr(2)+arr(3), 4), dfs(arr(2)+arr(4), 5), dfs(arr(2)+arr(5), 6) .... 으로 경우가 쪼개지고 
..
dfs(0+arr(n-1), n)은 return 문을 만나 종료됩니다.
따라서 퐁당퐁당 선택해서 더해지는 모든 경우를 흝을 수 있습니다.

혹시 잘못 된 점 있다면 피드백 부탁드립니다 😊 감사합니다 !!

**Comment by nukeC919** [comment]
두 방법 모두 정확하게 설명하셨네요! 좋습니다 :D
