### ISSUE TITLE
[초급반 3회차] N-Queen! (raonmire) 

### ISSUE THREAD

**Issue by Raon1123** [UNIST-Almight/PSStudy_21Fall#24]
[Code](http://boj.kr/04ec7df554cc4ff7a690c9119bc08903)

유명한 N-Queen 문제입니다. 
row를 기준으로 iteration을 돌리게 되는데요. 
column을 정하게 된다면 Queen을 놓아보고 `conflit` 함수를 통하여 문제가 되는지 여부를 판단합니다. 
Board에 직접 넣어 판단하는 것이 아닌, Queen의 위치에 따라 달라지게끔 설정하였습니다.

**Comment by ghost** [comment]
저는 전체 보드에 퀸을 넣으면서 했는데 이런 방법도 있었네요!

**Comment by docsom** [comment]
자료 안 보고 직접 구현하신 것 같아서 인상적이네요. 코드 잘 봤습니다
