### ISSUE TITLE
[초급반 3회차] A번 문제 코드 리뷰 (firebird)

### ISSUE THREAD

**Issue by ghost** [UNIST-Almight/PSStudy_21Fall#25]
[15649번 N과M](http://boj.kr/ff0831a6cd3f49cb9fec8d70fccdca8a)

깃헙과 코드 리뷰를 완전히 까먹고 있어서 이제야 처음 작성해 보네요...
ans 배열에 출력하고자 하는 수열을, dn 배열에 백트래킹을 할 수 있는 정보를 저장하는 식으로 했습니다.

```C
void nm(int x)
{
 if (dn[i] == 0)
 {
   dn[i] = 1;
   ans[x] = i;
   nm(x + 1);
   dn[i] = 0;
 }
}
```

**Comment by mskim-17** [comment]
깔끔하게 잘 짜셨습니다 👍👍

**Comment by mok0102** [comment]
맨 앞에 있는 
#pragma warning(disable:4996)
이 하는 역할이 뭔가요 ??
코드 잘 짜신 것 같습니다 ☺️☺️

**Comment by ghost** [comment]
> 맨 앞에 있는 #pragma warning(disable:4996) 이 하는 역할이 뭔가요 ?? 코드 잘 짜신 것 같습니다 ☺️☺️

scanf_s 대신 scanf를 사용하기 위해 scanf 사용시 발생하는 경고를 무시하는 코드입니다!
