### ISSUE TITLE
[초급반 3회차] C, D번 문제 코드 리뷰 (kts0921)

### ISSUE THREAD

**Issue by docsom** [UNIST-Almight/PSStudy_21Fall#26]
[C번 문제 암호 만들기](http://boj.kr/d8087a8c8e8e48f7a480cf218a92fb5b)
```c++
void func(int index, int pre, int vowel, int consonant) {
	if (index == L) {
		if (vowel > 0 && consonant > 1) cout << password << "\n";
		return;
	}
	for (int i = pre + 1; i < C; i++) {
		password[index] = arr[i];
		func(index + 1, i, vowel + isVowel[arr[i] - 'a'], consonant + !isVowel[arr[i] - 'a']);
	}
}
```

백트래킹 함수를 위처럼 참고 자료를 보고 짰습니다. 함수의 매개변수가 4개가 사용된 건 처음인데 매개변수가 많은 경우가 PS에서 흔한가요? 매개변수를 줄이는 쪽으로 최적화를 해야하는지 궁금합니다.

---

[D번 문제 N-Queen](http://boj.kr/4884228052b041cfb26d0473e9a83dc8)
이 문제도 자료를 보고 만들었습니다. 자유롭게 피드백 주시면 감사합니다.

---

30분 정도 늦게 올려서 죄송합니다..😢

**Comment by mskim-17** [comment]
C. 매개 변수 4개는 큰 문제가 되진 않지만, 줄이고자 한다면 `consonant`를 `L - vowel`로 대체하는 방법이 있을 것 같습니다.
D. 깔끔하게 잘 짜셨습니다! 👍👍

**Comment by mok0102** [comment]
D번 문제를 못 풀어봤었는데 코드가 깔끔해서 이해하기 편했습니다 !! 감사합니다 ☺️

**Comment by ghost** [comment]
D번 저보다 훨씬 깔끔하게 짜셨네요 부럽습니다!
