### ISSUE TITLE
[초급반 4회차] A, G번 문제 코드 리뷰 (kts0921)

### ISSUE THREAD

**Issue by docsom** [UNIST-Almight/PSStudy_21Fall#27]
[A번 문제 수 정렬하기 2](http://boj.kr/2e7b1319017f45c69f74ff87eaefe41a)
```c++
int arr[1000000];
int tmp[1000000];

void merge(int begin, int middle, int end) {
	int L, R, i;
	L = begin;
	R = middle + 1;
	i = begin;
	while (L <= middle && R <= end) {
		if (arr[L] < arr[R]) tmp[i++] = arr[L++];
		else tmp[i++] = arr[R++];
	}
	if (L > middle) {
		for (int j = R; j <= end; j++)
			tmp[i++] = arr[j];
	}
	else {
		for (int j = L; j <= middle; j++)
			tmp[i++] = arr[j];
	}
	for (int j = begin; j <= end; j++)
		arr[j] = tmp[j];
}

void mergeSort(int begin, int end) {
	if (begin < end) {
		int middle = (begin + end) / 2;
		mergeSort(begin, middle);
		mergeSort(middle + 1, end);
		merge(begin, middle, end);
	}
}
```

자료 참고해서 병합정렬을 짜봤습니다. 객프 수업 들었을 때도 소트를 짰었던 것 같은데 퀵소트였던 것 같네요. A번 문제는 퀵소트로 짜면 최악의 경우에서 시간 초과가 나온다고 해서 병합 정렬로 코드를 짰습니다.
arr이랑 tmp 둘다 1000000으로 선언해서 메모리를 조금 더 쓴 것 같은데 줄이는 방법이 있을까요?

---

[G번 문제 피보나치 수 3](http://boj.kr/a11a6f2bb6ff427cb8c29e12510e1d8b)

이번 주차의 주제인 분할정복을 사용하진 않았고 ["피사노 주기"](https://www.acmicpc.net/problem/9471)라는 개념을 써서 풀었습니다. 나중에 시간이 되면 분할정복을 활용하여 풀어보고 싶고 피사노 주기 문제도 풀어봐야 겠습니다.

**Comment by nukeC919** [comment]
[ A ]
arr tmp 둘다 1,000,000 로 선언한게 메모리 최소인게 아닌가 싶습니다.
또한 256MB 중 1MB 정도만 썼으니 괜찮습니다.

[ G ]
피사노 주기를 처음 알게됐는데 굉장히 심오하군요... 나중에 한번 공부해봐야겠습니다 :D
