### ISSUE TITLE
[초급반 4회차] B번 문제 코드 리뷰 (gracelee)

### ISSUE THREAD

**Issue by mok0102** [UNIST-Almight/PSStudy_21Fall#28]
[B번 문제 코드](http://boj.kr/b0cbd6c916844441a89c9c1110d46acc)
문제부터 이해가 가지 않아서 조금 해멨었는데, 다 숫자가 똑같을 때만 압축할 수 있고(합칠 수 있고) 그 외에는 모두 네개로 분할하여 압축을 하는 문제였음을 깨닫고 문제를 풀 수 있었습니다!
고생했던 부분은
`
for(int i=x_s;i<x_s+s;i++)
        for(int j=y_s;j<y_s+s;j++)
            if(arr[i][j]!=now){ // 하나라도 안 똑같으면(다똑같아야만 합칠 수 있다) 4개로 나눠서 재귀를 돌려라
                // 코드
            }
` 
처럼 for문이x_s안에 y_s가 도는 꼴이 되면 보통 글을 읽는 순서(왼쪽->오른쪽, 위->아래)대로 되지 않고 위에서 아래로 글을 읽는 순서(위->아래, 왼쪽-> 오른쪽)로 되서 합치는 순서또한 위에서 아래로 합쳐진다는 점이었습니다. 코드를 바꿔 보면서 바꿔야 된다는 것을 깨닫기는 했지만, arr[0][0] arr[0][1] arr[0][2]
arr[1][0] arr[1][1] arr[1][2]
이렇게 저장되어 있는 상황에서 x_s먼저 돌고 y_s가 그 안에서 도는 것이 왜 아닌지가 궁금합니다.

y_s가 돌고 그 안에서 x_s가 돈다면 배열 저장이 
arr[0][0] arr[1][0] arr[2][0]
arr[0][1] arr[1][1] arr[2][1]
이렇게 되어 있어야 하는 것이 아닌지 헷갈려서 이 부분을 잘 알고 계시는 분이 답해 주시면 좋겠습니다!

**Comment by nukeC919** [comment]
2차원 배열 arr[3][2] 가 있다고 할 때,
```
[
    [ 1 , 2 , 3 ] ,
    [ 4 , 5 , 6 ] ,
]
```
이렇게 저장될 겁니다.
이때 첫번째 인자는 위아래(y좌표) 를 담당하고 , 두번째 인자는 왼오(x좌표) 를 담당하기 때문에,
2차원 배열좌표는 저희가 쉽게 알아볼 수 있도록 `arr [ y ] [ x ]` 형식으로 저장합니다. xy순서가 아닌 yx 순서이죠.

또한 2차원 for 문을 돌릴때 우선순위가 x 먼저 돌고 y 시작하잖아요? 즉,
```
for y {
    for x {}
}
```
이렇게 한다면
```
[
    [ 1 , 2 , 3 ] ,
    [ 4 , 5 , 6 ] ,
]
```
이런 순서로 거쳐갑니다.
하지만,
```
for x {
    for y {}
}
```
이렇게 한다면
```
[
    [ 1 , 3 , 5 ] ,
    [ 2 , 4 , 6 ] ,
]
```
이렇게 위아래를 우선으로 거쳐가게 되겠죠.

상황에 따라서 2가지 중에서 고르는 연습을 많이 하시면 상당히 도움 됩니다. 특히 DFS,BFS 같은 부분에서요!

**Comment by mok0102** [comment]
와 …. 흑흑 너무 감사합니다 이해가 안갔는데 바로 갔어요 너무감사합니다 ㅠㅠ !!!!
