### ISSUE TITLE
[초급반 4회차] C번 문제 코드 리뷰 (raonmire)

### ISSUE THREAD

**Issue by Raon1123** [UNIST-Almight/PSStudy_21Fall#29]
[Code](https://www.acmicpc.net/source/share/9ecc0e25d37b4100ac13781ae6809b72)

`N*N` 정사각행렬 `mat`을 `B`번 곱하는것이 문제이다.
그냥 `B`번 곱하면 당연히 시간초과가 날 것이고, 어떻게 적절히 나누어서 곱하느냐가 포인트.
`mat`와 `mat`을 곱하면 2제곱이 되고, 2제곱을 2제곱과 곱하면 4제곱이 되고 ...
이렇게 2의 거듭제곱 꼴인 경우를 만들 수 있는데, 이진법으로 표현하게 되면 해당 위치가 1인 경우에만 정답에 곱하면 됩니다.

+ `ans` 행렬이 왜 다 0으로 assign 되지 않았느냐? 행렬의 Identity는 0이 아니라 Identity Matrix이죠.

**Comment by mskim-17** [comment]
각 부분마다 어떤 역할을 하는지 각주로 표기해 둬서 구조를 이해하기 편했습니다. assign을 활용해 vector를 초기화하는 방법에 대해 알게 되었네요 😯😯

**Comment by docsom** [comment]
shift연산으로 나누기 2를 하는게 신기하네요👍
