### ISSUE TITLE
[초급반 4회차] E번 문제 코드 리뷰 (cgw1999)

### ISSUE THREAD

**Issue by gwannuu** [UNIST-Almight/PSStudy_21Fall#30]
이문제를 풀려면 먼저 L-트로미노 타일링 문제에 대해 알아야 한다.

L-트로미노 타일링에 대한 내용은 https://wogud6792.tistory.com/64 에 자세히 나와있다

위 블로그를 읽은 후라면 L-트로미노 타일링으로 우리가 풀려는 문제는 항상 타일을 꽉 차게 배치할 수 있음을 알 수 있다.

하지만 이 문제같은 경우는 여기에서 더 나아가서 어떻게 꽉 차게 배치할 수 있는지에 대해서 까지 물어본다

그 답변은 다음과 같다.

처음 시작할 때 전체 타일을 가로세로 각각 이등분하여 네개의 영역으로 쪼갠다.
그렇다면 네 개의 영역 중에 단 하나의 영역만 빈칸이 아닌 타일을 가지고 있다
L-트로미노 타일링에 의해서 전체중 단 하나의 영역만 빈칸이 있으므로 가득 채울 수 있음이 보장된다

그렇다면 모두 빈칸인 나머지 세 영역에 대해서 
![image](https://user-images.githubusercontent.com/83270461/135871859-6f20f171-12fd-40b6-a28b-df709d41ce4a.png)
다음과 같이 L자 모양의 타일을 배치한다 (노란색). 흰색 타일은 배수구이다.(기존에 채워져있는 타일)

그렇다면 이제 다시 각각의 영역을 보면 한칸만 타일이 채워져있는 L-트로미노 타일링이 된다
네 영역 모두 다시 한칸씩만 타일이 채워져 있는 L-트로미노 타일링 문제가 되는것이다

따라서 각각의 영역에대해서 위와같은 방식으로 노란색 타일을 채우게 되면 모든 타일을 채울 수 있다!
(각각의 재귀의 종착점은 한변의 길이가 2인 정사각형꼴의 L-트로미노 타일링이다)

코드는 다음과 같다
http://boj.kr/0d34ab40babf439db21721e7ea21fd52

**Comment by mskim-17** [comment]
풀이에 대한 설명이 굉장히 자세하고, 각각의 함수가 하는 역할도 직관적으로 판단할 수 있는 좋은 코드네요 👍 
혹시 L-트로미노 타일링에 대해 더 관심이 있다면 [22359번 문제](https://www.acmicpc.net/problem/22359)와 [16128번 문제](https://www.acmicpc.net/problem/16128)도 읽어 보세요!
