### ISSUE TITLE
[중급반 5회차 A번] 이 문제를 어떻게 플로이드 와샬로 풀 수 있을까요? (flame623)

### ISSUE THREAD

**Issue by JinLover** [UNIST-Almight/PSStudy_21Fall#33]
풀이 코드: http://boj.kr/b41279fd8fbe45fdaea6c4621204ed9d

사실 플로이드 와샬을 공부하는 주간인데 플로이드 와샬 없이 풀게 되었습니다;;제 구현은 노드들간의 연결 정보를 인접행렬로 구현하고, 질문 단계에서 DFS를 이용하여 해당하는 값이 있는지 체크하도록 구현하였습니다.
하지만 아무리 생각해봐도 다른 노드들간의 최소 거리를 구하는 플로이드 와샬 알고리즘과 단순히 연결이 되어 있는지 아닌지 여부를 판별하는 이 문제가 어떠한 관계가 있는지 모르겠습니다.

**Comment by queuedq** [comment]
간선의 가중치를 0으로 잡고 플로이드 워셜을 돌리면, 거리가 무한인 정점 사이에는 경로가 없다는 의미이므로 연결되지 않았다고 판별해 줄 수 있고, 반대로 거리가 0인 정점끼리는 연결되어 있다고 생각할 수 있습니다. 말씀하신대로 DFS로 풀어도 되지만, 문제를 여러 가지 방법으로 모델링하는 방법을 생각해 보라는 차원에서 연습문제로 선정했습니다. D도 비슷하게 DFS만으로 풀리지만, B나 C는 플로이드 워셜을 사용해야 풀리는 문제이므로 두 문제에 도전해 보셔도 좋을 것 같아요!
