### ISSUE TITLE
[고급반 5회차] E번 문제 코드 리뷰 (mskim17)

### ISSUE THREAD

**Issue by mskim-17** [UNIST-Almight/PSStudy_21Fall#34]
https://www.acmicpc.net/source/share/0fa88c3aed1848d7987c139e20084248

이 문제의 답은 볼록 껍질 위에 있는 점 4개 (또는 3개)로 만들 수 있는 구역 중 가장 넓은 구역의 넓이를 찾음으로써 구할 수 있습니다. 볼록 껍질을 구한 이후에는 가능한 모든 대각선에 대해 볼록 껍질을 두 부분으로 나누고, 각 부분에 대해 삼각형의 크기를 가장 크게 하는 점을 삼분 탐색으로 찾아 넓이를 갱신하는 것을 반복해 최대 넓이를 O (n<sup>2</sup> log n)의 시간 복잡도 내에 구할 수 있습니다.

**Comment by queuedq** [comment]
삼각형의 크기를 가장 크게 하는 위치를 삼분탐색으로 찾았군요! 저는 투 포인터를 써서 찾았는데, 이 방법도 한번 생각해 보세요. 시간복잡도에서 로그를 뗄 수 있습니다.
