### ISSUE TITLE
[초급반 5회차] D번 문제 이분탐색 loop 관련 (gtod0104)

### ISSUE THREAD

**Issue by gdpark14** [UNIST-Almight/PSStudy_21Fall#35]
http://boj.kr/f2da201da36a433b9db317c24fcf47c7
```
while left<=right:
    mid=(left+right)//2
    if possible(mid):
        right=mid-1
    else:
        left=mid+1
```

이분탐색을 할 때 while left<=right 를 통해서 적절한 값을 찾아내는데 이 경우 최종적으로 원하는 값은 left에 저장 되는 것으로 이해했습니다 (가장 마지막으로 적합한 mid가 left에 저장이 됩니다) . 그렇다면 'while left<=right로 loop를 계속 돌리고 최종적으로 원하는 값은 left에 있다' 이런식으로 하나의 공식처럼 알고 있어도 되는 걸까요?

**Comment by docsom** [comment]
코드 잘 봤습니다. 저는 아직 안 푼 문제라서 답은 못 드릴것같네요..😢

**Comment by mskim-17** [comment]
문제의 목적에 따라서 달라집니다. 예를 들어 [Ax+Bsin(x)=C ②](https://www.acmicpc.net/problem/14786) 문제와 같이 구해야 하는 답이 실수인 경우에는 "right와 left의 차이가 충분히 작을 경우"를 loop의 조건문으로 삼아야 하는 경우도 있습니다. 아래 글이 의문을 어느 정도 해소할 수 있지 않을까 합니다 :D

https://www.acmicpc.net/blog/view/109
