### ISSUE TITLE
[초급반 5회차] C, E번 문제 코드 리뷰 (kts0921)

### ISSUE THREAD

**Issue by docsom** [UNIST-Almight/PSStudy_21Fall#36]
[C번 크게 만들기](http://boj.kr/10a99fe713c4400a8eb80a24bb51ee16)
deque를 사용했고 N자리 숫자를 한 자리씩 맨 뒤에 넣었고 앞에 있는 숫자가 작으면 pop 시켰습니다.
출력은 반대로 맨 앞에서부터 N - K번 출력했습니다.

---

[E번 책 나눠주기](http://boj.kr/6e6fd80670d847d9bbae86547912ec1c)
책 범위가 a에서 b인데 b를 기준으로 오름차순으로 정렬한 후 책을 나눠주게 짰습니다.

---

편하게 피드백 주세요~~

**Comment by nukeC919** [comment]
되게 깔끔하게 짜셨네요. 좋습니다! :D

**Comment by queuedq** [comment]
E번 저는 a를 기준으로 정렬해서 풀었는데, b를 기준으로 정렬하는 풀이도 있을 줄은 몰랐네요. 한 문제에 여러 가지 풀이가 있다는 게 재밌네요 ㅎㅎ 더 나아가서 우선순위 큐를 이용해서 O(nlogn) 시간에 푸는 방법도 있으니까 관심 있다면 한번 찾아보세요!
