### ISSUE TITLE
[초급반 5회차] C번 문제 코드 리뷰 (gracelee)

### ISSUE THREAD

**Issue by mok0102** [UNIST-Almight/PSStudy_21Fall#37]
풀기는 풀었는데 조금 이해가 안 갔던 부분을 문제 풀이 세션을 듣고 이해해서 풀이합니다!!
[C번](http://boj.kr/e4e5147175ea4603acd8a90addc41f41)

숫자를 받고, 앞에서부터 읽어가면서 스택에 하나씩 넣습니다. 스택은 정답을 가지고 있습니다.
스택의 맨 뒷자리 숫자를 빼고 현재 숫자를 넣는 거랑, 그냥 현재 숫자를 넣는 거랑 어떤 것이 더 이득인가? 를 생각하면 되는데, 이거는 맨 뒷자리 숫자가 현재 i번째 숫자보다 작으면 무조건 빼고 현재 숫자를 넣는 것이 낫고, 아니라면 그냥 붙이는게 낫습니다!! (41 되는거랑 4빼고 1x되는 것 중에서는 4를 안 빼고 1을 그대로 붙이는 게 나은 것처럼)

풀이를 찾아보니 deque를 많이 써서 처음 낼 때는 왜 그런가 싶었고.. 풀이 세션에서 stack을 쓰면 된다고 말씀해 주셔서 stack을 써서 해 봤는데, 왜 deque를 쓰는지 이해할 수 있었습니다 괜히 사람들이 deque를 쓰는 게 아니었습니다. stack은 위에서 아래로밖에 읽을 수가 없어서 결국 다 뽑아서 다른 데 저장해서 출력하는 방법밖에 없는데,(저는 그래서 스택을 두개 썼습니다) deque를 쓰면 stack처럼 back(stack에서는 top)이랑 push_back, pop_back을 다 쓸 수 있으면서 출력할 때 딴 데 저장 안하고 바로 순서대로 읽을 수 있어서 deque를 사용했던 것이라는 걸 느낄 수 있었습니다!

읽어주셔서 감사합니다!!

**Comment by mok0102** [comment]
혹시 저 char a[i]를 읽을 때 1은 49 아스키 코드로 읽히는데 이걸 바로 1로 읽을 수 있는 방법이 있나요..?

**Comment by docsom** [comment]
저는 deque를 썼는데 확실히 stack은 마지막 출력때 좀 귀찮아 보이네용

**Comment by nukeC919** [comment]
문자를 바로 숫자로 읽는 함수들이 있기는 합니다만... ( atoi , stoi 등등 )
다루기가 좀 어려운 함수들이라 그냥 아스키코드로 조작하는게 가장 좋은 방법입니다.

**Comment by queuedq** [comment]
참고로 아스키 코드 외울 필요 없이 `a[i] - '0'` 이런 식으로 실제 숫자값을 구할 수 있어요. 가령 '5' - '0' 은 각각 아스키 코드가 53, 48이니까 5가 돼요.

문제 풀이 세션에서는 stack을 말씀드렸는데, 출력할 때 불편하니까 그냥 vector를 쓰고 push_back, pop_back 연산을 사용하시면 될 것 같아요!
