### ISSUE TITLE
[초급반 6회차] C번 문제 코드 리뷰 (gtod0104)

### ISSUE THREAD

**Issue by gdpark14** [UNIST-Almight/PSStudy_21Fall#38]
http://boj.kr/448c7fe4a9934dfc9bedf8b02e79cdfc

앞의 A,B번 문제와 달리 위의 문제는 포인터 하나는 앞에서 시작하고 하나는 뒤에서 시작하도록 풀었습니다. 이 생각을 하기 까지 다소 시간이 걸렸는데

1. 한 배열에서 포인터가 둘 다 앞에서 시작하는 경우
2. 한 배열에서 포인터 하나는 앞, 하나는 뒤에서 시작하는 경우
3. 배열 두개를 쓰는 경우

이렇게 투포인터를 접근 할 수 있을 것 같은데 접근 방법을 쉽게 알아챌 수 있는 방법이 있을까요?

**Comment by wbjeon2k** [comment]
탐색하는 구간 [s,e] 가 있을 때,
s, e 각각 감소/증가 하기만 한다는 것을 관찰하는게 중요한것 같습니다.

1806 번은 s,e가 증가/증가 라서 둘 다 포인터가 앞에서 시작해서 증가하고,
용액 문제는 s는 증가, e는 감소라서 포인터 s는 앞에서 부터 증가하고, e는 반대로 감소만 하는 상황이죠.

s,e의 성질을 쉽게 알아챌 수 있는 방법은 없는것 같습니다
s,e 의 성질을 관찰 했다는거 자체가 투포인터 풀었다는 말과 비슷한거 같아서요...
저도 투포인터 잘 못풉니다 ㅠ 고수의 길은 멀고도 험한것 같아요

**Comment by nukeC919** [comment]
투포인터가 좀 접근하기 어려운 알고리즘이긴 합니다 ㅠ
그리고 알고리즘 외로 팁 하나 드리자면,
```py
import sys
input = sys.stdin.readline
```
이렇게 쓰시면 `sys.stdin.readline()` 이 길다란 코드를 `input()` 으로 쓸 수 있습니다!
코드도 좀 더 깔끔해지고 읽기 쉬워질겁니다 :D
