### ISSUE TITLE
[초급반 6회차] B번 문제 리뷰 (gracelee)

### ISSUE THREAD

**Issue by mok0102** [UNIST-Almight/PSStudy_21Fall#39]
[B번](http://boj.kr/421cbe8511104e7589a9960e52625955)
for문으로 투포인터의 첫번째 포인터(st)를 정해주고, while문을 통해 조건을 만족할 때까지 두번째 포인터(en)을 늘려서 정해줍니다.
궁금한 점은 투포인터로 O(n^2)을 O(n)으로 처리할 수 있게 해준다고 했는데, for문으로 st를 정하고 그 안에서 while문이 돌아가면 이게 왜 O(n)이 되는 건지 궁금합니다. 그래서 시간 초과가 났던 코드가 왜 시간 초과가 났는지, 제 코드는 O(n^2)으로 돌아가고 있는건지가 궁금합니다.!

**Comment by wbjeon2k** [comment]
1. 코드
현재 코드는 15번째 줄에서 en=st; 를 매번 새로 하고 있네요.
while 문의 핵심은 모든 en이 끝에 닿았을 때 break를 하는 것인데, en을 매번 갱신하면 중복해서 찾게 됩니다.
en은 고정되어 있어야 합니다.
현재 코드는 O(N)개의 st에 대해 O(N) 개의 en을 다시 찾는거라서 O(N^2) 이 됩니다.
en=st; 를 빼면 오답이 나오는걸 봐서, 다른곳도 손을 봐야할 것 같습니다.

2. 왜 투포인터는 O(N) 일까?

투 포인터 문제의 핵심은 (제 생각에) st, en(st<=en) 의 O(N^2) 위치 조합들 중,
실질적으로 탐색할 필요가 있는 경우의 수가 O(N) 인 특수한 성질을 관찰 하는것 이라고 생각합니다.

[st,en] 에서 en이 한 칸 증가를 할 때, 현재 st보다 작은 모든 st들은 신경 쓰지 않고 st를 증가시키며 탐색을 하다가,
구간의 합이 S 이하로 떨어지면 st를 고정하고 다시 en을 증가시키는 과정을 반복하는게 이 문제의 해법이죠.

en이 움직이는 횟수가 최대 N 번, st가 움직이는 횟수가 최대 N번 이라서
가능한 (st,en) 의 조합은 O(N^2) 이 맞지만,
탐색하는 (st,en) 의 조합은 O(N) 으로도 충분한 상황입니다.

-----------------
조금 부족할 수 있는데, 다른 분들의 생각도 더해주시면 감사하겠습니다!

**Comment by nukeC919** [comment]
윗분께서 깔끔하게 다 설명해주셔서 할말이 없네요...
투포인터는 각각의 포인터가 왔다갔다 하지 않고
단방향으로 움직인다는 걸 생각하시면서 짜시면 편하실 것 같아요 :)
