### ISSUE TITLE
[초급반 1회차] DP 프로그램의 점화식을 어떻게 생각해 낼 수 있을 까요?

### ISSUE THREAD

**Issue by gdpark14** [UNIST-Almight/PSStudy_21Fall#4]
[12865] 배낭 문제 http://boj.kr/e3ece5ed270e49b38d34c7082646aca3

```python
        if items[i][0]>j:
            sheet[i][j]=sheet[i-1][j]
        else:
            need_weight=items[i][0]
            add_value=items[i][1]
            sheet[i][j]=max(sheet[i-1][j],sheet[i-1][j-need_weight]+add_value)
```

이런 문제를 처음 볼 때 2차원 배열에서 배낭의 무게를 x축으로 한다는 생각을 어떻게 하는 걸까요...? 도저히 떠오르지가 않을 것 같은데 이렇게 유명한 문제는 여러번 접해서 외우는 방식으로 공부해야 할까요?

또한 저기서 sheet[i-1][j-need_weight] 를 통해 현재 들어갈 물건의 무게를 비워주는 방식으로 식을 세웠는데 이것 말고 다른 방법이 있을까요? if를 통해서도 뭔가 만들어 낼 수 있을 것 같은데 코드가 복잡해질까요?

**Comment by wbjeon2k** [comment]
*이슈에 회차 / 코드 리뷰 라벨 달아주세요!*

DP는 가장 일찍 접하는 주제이면서도 가장 어려운 주제라고 생각합니다.
제 개인적인 생각이지만, 일반화 해도 큰 문제 없을것 같습니다.

DP 문제를 많이 풀면 문제를 DP/점화식 형태로 모델링 하는 여러가지 방법을 배울 수는 있지만, 점화식을 단번에 떠올리는 일반적인 방법은 없습니다.

대신, DP 문제들의 효율적인 접근을 배우기에 좋은 자료를 드리도록 하겠습니다.
[MIT OCW 6.046J](https://youtu.be/NzgFUwOaoIw?list=PLUl4u3cNGP6317WaSNfmCvGym2ucw3oGp&t=947)
링크에 있는 시간부터 DP 문제에 대한 설명이 나오는데, 참고하시면 좋을것 같습니다.
DP 문제를 모델링 하는 방법을 5단계로 나눠서 설명을 하는데, 저는 매우 인상적으로 봤던 자료입니다. 도움이 되셨으면 좋겠습니다.

**Comment by jjh94210** [comment]
저도 @gdpark14 님께서 질문해 주신 부분이 고민이었는데 @wbjeon2k 님께서 올려주신 자료 잘 공부해 보겠습니다ㅎㅎ 🥇
