### ISSUE TITLE
[초급반 7회차] A, D번 문제 코드 리뷰 (kts0921)

### ISSUE THREAD

**Issue by docsom** [UNIST-Almight/PSStudy_21Fall#40]
[A번 무한 수열](http://boj.kr/f2557c8b8bd8494381094a81f42c07f3)
DP로 문제를 풀었습니다. unordered_map은 안 써본 것 같아서 사용해봤는데 이 문제에서는 map을 쓰나 코드에 차이는 없는 것 같습니다.

---

[D번 XOR Sum](http://boj.kr/f8f26d0bf3464a198253d578159c95e1)
1학기 때 풀었던 문제인 것 같습니다. priority_queue를 사용했고 insert할 때마다 출력할 결과값을 수정해서 가지고 있는 방식입니다.

---

편하게 피드백 주세요~

중간 끝나고 과제가 너무 많아져서 힘드네요 ㅜㅜ 저번 회차는 저도 빠졌는데 다른 분들도 참여율이 저조한 걸 보니 다들 바쁘신 것 같아요. 모두 힘냅시다!👍

**Comment by mskim-17** [comment]
두 코드 모두 깔끔하게 짜신 것 같습니다. 👍 무한 수열 문제에서 n의 범위가 매우 큼에도 i/P, i/Q 값이 빠르게 줄어들어서 제한된 시간/공간복잡도 내에 풀 수 있다는 점이 신기하네요 😯😯
