### ISSUE TITLE
[초급반 8회차] A번 문제 질문

### ISSUE THREAD

**Issue by gwannuu** [UNIST-Almight/PSStudy_21Fall#41]
1. http://boj.kr/cd8c7c3685b34ccea36762dbddc32c6d
위 코드가 제가 처음으로 제출한 코드입니다

이분 탐색을 사용하였는데도 계속해서 97%에서 시간초과가 나서
다른 코드를 참고해서 다시 코딩해보았습니다

2. http://boj.kr/135d26ec19a1446ea1ad8c8e9bb37fb0
위 코드가 시간초과없이 통과한 코드입니다

제 생각으로는 1번 코드나 2번코드나 둘다 비슷하게 보이고 둘다 통과해야 할것같은데 1번코드는 통과하지 못한 이유가 궁금합니다

------

이 문제같은 경우 코드에서 제일 위치값이 작은 지점을 첫번째 공유기를 설치하는 지정으로 정하고 시작합니다. 위치값이 제일 작은 지점을 p(1)이라고 하겠습니다. 

궁금한 점은 위치값이 작은 지점부터 큰 지점까지 공유기를 설치할수 있을지 없을지 탐색한다고 가정할 때  p(1)에 공유기를 설치하는 경우보다 p(1)에 공유기를 설치하지 않는 경우가 output이 더 큰 경우가 있을 까요? 또,그러한 이유까지 설명이 가능할까요?

**Comment by mskim-17** [comment]
반복문의 조건이나 초기값을 잘못 설정한 경우 무한 루프가 발생할 수 있습니다.
첫 코드에서는 다음과 같은 입력이 주어졌을 때 무한 루프가 발생합니다. 
```
2 2
0
1
```
46번째 줄의 반복문 조건 `right-left==1`를 `right-left<=1`로 바꾸거나, 33번째 줄에서 `left`의 값을 `0`으로 바꾸면 통과합니다.
