### ISSUE TITLE
[초급반 1회차] C, D번 문제 코드 리뷰 (kts0921)

### ISSUE THREAD

**Issue by docsom** [UNIST-Almight/PSStudy_21Fall#5]
[C번 문제](http://boj.kr/1cee64bb9dac437c94ccb8d8135f73d5)
풀이가 떠오르지 않아 공지에 있는 자료를 참고했습니다. 코드 보시고 피드백 주시면 좋겠습니다.

---

[D번 문제](http://boj.kr/38990ae43a0c4f6f960bc574571983f9)
```
int Knapsack[101][100001];
int weight[101];
int value[101];
```
이 문제도 자료를 참고했습니다. 저는 메모리가 41476KB 사용됐는데 혹시 2차 배열 때문일까요? 2차 배열 없이 풀 수 있는 방법도 있는지 궁금합니다.

---
라벨을 붙이려고 하는데 None yet으로 뜨고 클릭 안됩니다. 권한이 없는건가요?

**Comment by wbjeon2k** [comment]
C 번 LCS 는 딱히 덧붙일 말이 없는것 같습니다.

D번은 네, knapsack 문제는 메모리 최적화가 가능한 문제입니다.
힌트는 i 번째 row 는 i-1 번째 row 의 정보 만을 필요로 한다는 점 입니다.
잠깐 생각 해보시고 아래 링크 읽어보시면 됩니다!
[Link1](https://www.geeksforgeeks.org/space-optimized-dp-solution-0-1-knapsack-problem/?ref=rp)
[Link2](https://www.geeksforgeeks.org/0-1-knapsack-problem-dp-10/)

**Comment by nngm** [comment]
저는 C번 이렇게 했습니다
참고하실 거면 참고하세요
```
    dp[i][j] = str1[i] == str2[j];
    if (i)
        dp[i][j] = dp[i][j] > dp[i-1][j] ? dp[i][j] : dp[i-1][j];
    if (j)
        dp[i][j] = dp[i][j] > dp[i][j-1] ? dp[i][j] : dp[i][j-1];
    if (i && j)
        dp[i][j] = dp[i][j] > dp[i-1][j-1] + (str1[i] == str2[j]) ? dp[i][j] : dp[i-1][j-1] + (str1[i] == str2[j]);
```
