### ISSUE TITLE
[중급반 1회차] B번 문제 코드 리뷰 (ace9804)

### ISSUE THREAD

**Issue by DDoubleA** [UNIST-Almight/PSStudy_21Fall#6]
[2580번 스도쿠] http://boj.kr/840d5dcdbb7347e58cd85fcdc8d3fcda

table : 9x9 스도쿠 판, save : 채워야 하는 곳(0인 값들 index), emptynum : 0인 값 개수
row : 각 row에 1부터 9까지 수 중 어떤 것들이 있는지 기록
column : 각 column에 1부터 9까지 수 중 어떤 것들이 있는지 기록
square: 각 3x3 square에 1부터 9까지 수 중 어떤 것들이 있는지 기록

처음 input을 받을 때 table에 저장함과 동시에 row, column, square, save 등을 기록하고
이후 backtracking을 하며 save에 기록했던 위치에 들어갈 수 있는 수를 계속해서 찾아갑니다. emptynum만큼 빈칸을 채우면 출력 후 종료합니다.

**저도 label이 안되네요ㅠ**

P.S. 재귀 문제는 계속 헷갈리네요ㅠ 재귀 문제 푸는 팁이 있으면 알고싶습니다.!

**Comment by mskim-17** [comment]
개인적으로 처음 풀 때 굉장히 애를 먹었던 문제인데, 각 숫자의 사용 여부를 row, column, square라는 배열을 만들어 판단한 것이  인상 깊었습니다. 각 칸을 탐색할 때마다 가능한 숫자를 확인하는 것보다 더 깔끔한 구현인 것 같습니다.

**Comment by Raon1123** [comment]
스도쿠 문제는 SAT문제로 이는 NP문제이기에 효과적인 알고리즘이 현재로써는 없습니다.
그래서 모든 경우의 수를 빠짐 없이 효과적으로 탐색하는 것이 이 문제에서 요구됩니다.
row, column, square을 통하여 만족가능성 여부를 효과적으로 탐색하는 것이 이 코드에서 흥미로운 점으로 보입니다.
만약 이러한 SAT문제를 backtracking을 통해 탐색하는 것에 관심이 있으시다면 DPLL알고리즘을 공부하시면 보다 효과적으로 해결하실 수 있습니다.

스도쿠에 관심 있으면 관련 논문
https://www.lri.fr/~conchon/mpri/weber.pdf
