### ISSUE TITLE
[초급반 1회차] B번 문제 코드 리뷰 (raonmire)

### ISSUE THREAD

**Issue by Raon1123** [UNIST-Almight/PSStudy_21Fall#7]
[B번 문제 풀이](http://boj.kr/de7fb246f1644fffa083e7d676d1301f)

연속된 부분 합을 찾는데요.
최선의 경우가 되는 경우를 항상 기록하고, 그 최선의 경우를 `ans`에 저장하여 순회를 마치면 출력합니다.

**Comment by jjh94210** [comment]
매크로 사용이 인상 깊은 코드군요 👍

**Comment by mok0102** [comment]
#define, typedef을 사용해서 코드가 더 깔끔하게 보이는 것 같아요!! 직접 사용해본 적은 없는데 이 코드 보면서 저두 사용해봐야겠습니다 😊

**Comment by docsom** [comment]
algorithm 헤더를 안쓰고 define으로 max  정의하신게 인상적이네요 👍

**Comment by gwannuu** [comment]
define max는 앞으로저도 자주 사용해야겠네요 :)

**Comment by queuedq** [comment]
저는 define으로 매크로 정의해서 사용하는 것보단 algorithm 헤더에 있는 min, max 사용을 추천드립니다. 실제 개발할 때 매크로는 디버깅도 힘들고 원치 않는 사이드이펙트가 생길 수 있기 때문에 웬만하면 사용하지 않는 것이 좋습니다. PS 문제를 풀 때는 큰 영향이 없지만, 어차피 기존에 있는 기능이니 굳이 매크로를 정의하는 것보다 이미 있는 기능을 사용하는 것이 낫겠죠. algorithm 헤더에는 min, max 말고도 sort, swap, fill, reverse, find, min_element/max_element 같은 PS에 유용한 함수들이 많이 있기 때문에 꼭 알아두는 것이 좋습니다!

**Comment by queuedq** [comment]
추가로, PS에서 자주 사용되는 매크로를 하나 알려드리자면, 다음과 같은 all 매크로가 있습니다.
```c++
#define all(x) (x).begin(), (x).end()
```
용도는, vector 등을 정렬하거나 lower_bound를 이용해서 이분탐색할 때 시작 지점과 끝 지점을 입력해야 하는데, 그걸 `sort(vec.begin(), vec.end())` 대신 `sort(all(vec))` 과 같이 짧게 입력하는 용도로 씁니다. 두 개의 인자를 마치 하나인 것처럼 만들어야 하기 때문에 매크로를 사용하는 것이죠.

이처럼 함수로 처리하기 어려운 경우가 아니면 매크로는 비추천드립니다. 대신 함수를 정의하거나 기존 라이브러리를 불러와서 사용해 주세요.

**Comment by DDoubleA** [comment]
매크로 기능이 있다는 것만 알았지 사용해본 적이 없는데 생각보다 유용하게 쓰이네요 감사합니다!

**Comment by ahnjongmin** [comment]
매크로 기능 사용하는 좋은 예시를 본 것 같네요. 잘 배워갑니다!
