### ISSUE TITLE
[초급반 1회차] B번 문제 코드 리뷰 요청 (jjh94210)

### ISSUE THREAD

**Issue by jjh94210** [UNIST-Almight/PSStudy_21Fall#8]
[소스코드](https://www.acmicpc.net/source/share/5ade7afa8faa4a8db8330771db772e20)

현재까지의 부분합이 이전 부분합보다 더 커지는 경우를 반영해서 코드를 작성하였습니다.

DP 문제는 아직 많이 어렵습니다 ㅠㅠ

**Comment by mskim-17** [comment]
num 배열이 입력을 저장하는 역할과 현재까지의 최대 부분합을 저장하는 역할을 동시에 하는 게 신기하네요 😯😯 DP 식도 깔끔하게 잘 짜신 듯 합니다.

**Comment by Raon1123** [comment]
저장공간을 입력을 받은 공간에 바로 처리하여 적은 공간으로 효과적으로 해결한 코드로 보입니다. :D``

**Comment by mok0102** [comment]
dp[i-1]이 음수일때 dp[i] 값을 초기화해주지 않아도 저장되어 있는 게 굉장히 인상 깊습니다 !! max를 찾을 떄에도 for문을 하나 더 쓰시지 않고 한번에 해결한 것도 멋있습니다 ☺️ 저두 이렇게 짤 수 있었으면 좋겠습니다 !!

**Comment by jjh94210** [comment]
답변해주신 @mskim-17 @Raon1123 @JungMok-Lee 님 모두 감사드립니다 👍
