### ISSUE TITLE
[중급반 1회차] A번 문제 코드 리뷰 (flame623)

### ISSUE THREAD

**Issue by JinLover** [UNIST-Almight/PSStudy_21Fall#9]
처음에 접근할때는 2차원 배열을 만들어서 하는게 어떨까 생각하다가, 메모리와 시간을 많이 소요할 것 같아서 다른 방식으로 정보를 저장하기로 했습니다.

시간초과 코드: http://boj.kr/73601ead43b2443988b6c0e4b6a33e55
이 코드는 이미 퀸이 들어간 x,y좌표를 저장한 후, 한칸씩 이동하며 이 칸에 퀸이 놓일수 있는지를 판별하는 코드입니다.
그러나 코드를 개선해 봐도 시간 초과가 계속 발생해, 여러 질문들을 찾아보니 새 퀸을 놓을 때 반복문으로 판별하는것보다 퀸이 들어갈 수 있는 배열을 만드는게 더 빠르다는걸 알게 되었습니다.

정답 코드: http://boj.kr/265d746d225a49a286c8ca8364c32a29
그렇게 배열 Q를 만들고, 인덱스는 퀸이 놓인 행을, 저장된 값은 퀸이 놓인 열을 뜻하도록 만들었습니다. 기존 퀸과의 체크도 현재 행까지만 하니 시간초과를 해결할 수 있었습니다.

문제를 풀면서 궁금했던 점이 많았는데요,
1. 처음에는 2차원 배열을, 다음은 퀸의 좌표를 그리고 마지막은 형태만 조금 바뀐 1차원 배열로 데이터 저장 방식이 바뀌었습니다. 문제를 풀 때 적합한 데이터구조를 찾는 방법이 있을까요?
2. 한번의 back 함수 실행시에 들어가는 시간은 이중 반복문이 있으므로 n^2의 시간이 든다고 생각했는데(이게 맞나요?), 이러한 백트래킹 문제에서 어디까지 백트래킹이 들어가고 나오는지, 총 몇번의 back 함수가 실행되는지에 대해서는 정량적으로 알아낼 수 있는 방법이 있을까요?
3. 항상 하게되는 질문인 것 같지만 어떻게하면 여기서 코드를 더 개선시킬수 있을까요? 또한 python으로는 결국 시간초과를 해결하지 못해 pypy로 제출했는데 파이썬으로는 이 문제를 시간 내에 해결할 순 없을까요?

**Comment by mskim-17** [comment]
전역 변수 N은 함수의 변수 R로 대체할 수 있고, 배열 Q는 함수의 인자로 넘겨주지 않아도 될 것 같습니다. 

2) 실행 시간이 다항 시간이 아니라는 것까지는 말씀드릴 수 있는데 정확히 분석하는 방법은 잘 모르겠습니다. 아마 O(n!) 정도가 아닐까 싶습니다. 

3)  첫 행에 놓인 Q의 위치가 정중앙이 아닐 경우 좌우 대칭되는 케이스도 있다는 점에 착안해 시간을 절반 정도 단축시킬 수 있으며, Python으로도 시간 내에 해결할 수 있음을 확인했습니다. (가장 편하게 해결하는 방법은 N<15인 N에 대해 모든 Q를 미리 계산헤 두는 것이긴 합니다... 😂)

- http://boj.kr/a9c878c191694e19bc729b7eb3c9a22d

**Comment by queuedq** [comment]
N-Queen 문제를 푸는 더 빠른 방법은, 현재 칸에 퀸을 놓을 수 있는지 여부를 O(N)이 아니라 O(1)에 판별하는 겁니다. O(N) 판별은 시간 초과가 날 줄 알았는데 의외로 시간 안에 통과가 되나보네요. O(1) 판별을 하려면 어떤 열/대각선을 이미 사용했는지를 boolean 배열로 관리하면 됩니다. mskim-17 님 코드가 해당 방식을 사용하니 참고해 주세요. 제 코드도 첨부해 둡니다.
http://boj.kr/2d4251248127495ebe0a426119f1d300

**Comment by DDoubleA** [comment]
양방향 대각선을 어떻게 O(1)으로 판별할까 했는데 i+j 랑 i-j+N으로 간단히 체크가 가능하네요. 생각해보면 열 판별하는 거랑 똑같은데 어렵게 생각했었네요ㅠ
